# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\downloadFile.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self):
        self.wd=QtWidgets.QMainWindow()
        self.setupUi(self.wd)
    def show(self):
        self.wd.show()
    def close(self):
        self.wd.close()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(275, 282)
        self.files = QtWidgets.QListView(Form)
        self.files.setGeometry(QtCore.QRect(10, 40, 256, 192))
        self.files.setObjectName("files")
        self.download = QtWidgets.QPushButton(Form)
        self.download.setGeometry(QtCore.QRect(90, 10, 75, 23))
        self.download.setObjectName("download")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 250, 251, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "下载界面"))
        self.download.setText(_translate("Form", "下载"))
        self.label.setText(_translate("Form", "下载进度："))
