# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\reportError.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def __init__(self):
        self.wd=QtWidgets.QMainWindow()
        self.setupUi(self.wd)
    def show(self):
        self.wd.show()
    def close(self):
        self.wd.close()
    def setupUi(self, reportErrorWD):
        reportErrorWD.setObjectName("reportErrorWD")
        reportErrorWD.resize(238, 141)
        self.widget = QtWidgets.QWidget(reportErrorWD)
        self.widget.setGeometry(QtCore.QRect(10, 20, 220, 113))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.modifyEquipment = QtWidgets.QPushButton(self.widget)
        self.modifyEquipment.setObjectName("modifyEquipment")
        self.verticalLayout_3.addWidget(self.modifyEquipment)

        self.retranslateUi(reportErrorWD)
        QtCore.QMetaObject.connectSlotsByName(reportErrorWD)

    def retranslateUi(self, reportErrorWD):
        _translate = QtCore.QCoreApplication.translate
        reportErrorWD.setWindowTitle(_translate("reportErrorWD", "维修上报"))
        self.label_2.setText(_translate("reportErrorWD", "选择你要上报的设备："))
        self.comboBox.setItemText(0, _translate("reportErrorWD", "设备1"))
        self.comboBox.setItemText(1, _translate("reportErrorWD", "设备2"))
        self.comboBox.setItemText(2, _translate("reportErrorWD", "设备3"))
        self.label_3.setText(_translate("reportErrorWD", "选择你要上报问题类型："))
        self.comboBox_2.setItemText(0, _translate("reportErrorWD", "硬件问题"))
        self.comboBox_2.setItemText(1, _translate("reportErrorWD", "软件问题"))
        self.comboBox_2.setItemText(2, _translate("reportErrorWD", "未知错误"))
        self.label.setText(_translate("reportErrorWD", "备注："))
        self.lineEdit.setPlaceholderText(_translate("reportErrorWD", "请将问题描述输入与此"))
        self.modifyEquipment.setText(_translate("reportErrorWD", "上报维修"))
